providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs-22_x", "nodePackages.pnpm"]

[phases.install]
cmds = ["npx pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["npx pnpm run build"]

[start]
cmd = "node server.js"
