"use strict";

/**
 * Register a Windows Scheduled Task that runs the flash-arb scan on a cadence.
 *
 * WHY A SCHEDULE AND NOT A LOOP
 * -----------------------------
 * A background `while(true)` loop dies with the terminal, ties up a shell, and
 * is easy to forget - and a scan that silently stops is worse than one that
 * never ran, because the history silently develops a gap. Task Scheduler
 * survives reboots and logon state, so the dataset grows whether or not this
 * project is open.
 *
 * WHY 30 MINUTES
 * --------------
 * Base blocks are ~2s. Scanning faster mostly re-reads the same state while
 * burning the free RPC endpoints, which shows up as throttled runs and low
 * coverage - i.e. it degrades the data it is meant to collect. Thirty minutes
 * samples a genuinely different market state each time.
 *
 * Usage
 *   node scripts/schedule-scans.js install          (default 30 min)
 *   node scripts/schedule-scans.js install -Minutes 15
 *   node scripts/schedule-scans.js status
 *   node scripts/schedule-scans.js uninstall
 */

const path = require("path");
const fs = require("fs");
const os = require("os");
const { execFileSync } = require("child_process");

const TASK_NAME = "TradeArena-FlashArb-Scan";
const ROOT = path.join(__dirname, "..");
const LOG_DIR = path.join(ROOT, "data", "logs");
const SCRIPT = path.join(__dirname, "scan-flashloan-arb.js");
const NODE = process.execPath; // the exact node running this, not a bare "node"

const args = process.argv.slice(2);
const cmd = args[0] || "status";
const minutesArg = args.indexOf("-Minutes");
const MINUTES = minutesArg !== -1 ? Number(args[minutesArg + 1]) : 30;

function psQuote(s) {
  return "'" + String(s).replace(/'/g, "''") + "'";
}

function run(cmdLine) {
  return execFileSync("powershell.exe", ["-NoProfile", "-Command", cmdLine], {
    encoding: "utf8",
  }).trim();
}

/**
 * Run a PowerShell script from a TEMP FILE rather than -Command.
 *
 * The arguments to this task contain a quoted path and a quoted string, and
 * nesting that inside a -Command string built in JS collapses in several
 * different places - `node.exe` ends up registered with an EMPTY Argument, and
 * Task Scheduler then fails with 267009 ("could not start") having written no
 * log line at all. Writing the script to disk removes every layer of quoting
 * between this file and the task definition.
 */
function runScript(psBody) {
  const tmp = path.join(
    require("os").tmpdir(),
    `flasharb-task-${process.pid}-${Date.now()}.ps1`,
  );
  fs.writeFileSync(tmp, psBody, "utf8");
  try {
    return execFileSync(
      "powershell.exe",
      ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", tmp],
      { encoding: "utf8" },
    ).trim();
  } finally {
    try {
      fs.unlinkSync(tmp);
    } catch (e) {
      /* best effort */
    }
  }
}

function install() {
  if (!Number.isFinite(MINUTES) || MINUTES < 5) {
    console.error(`Refusing a ${MINUTES}-minute interval. Minimum 5 minutes.`);
    console.error("Base blocks are ~2s; anything faster re-reads the same state and");
    console.error("burns RPC quota without adding information.");
    process.exit(1);
  }

  const logPath = path.join(LOG_DIR, "scan.log");
  const errPath = path.join(LOG_DIR, "scan-error.log");
  fs.mkdirSync(LOG_DIR, { recursive: true });

  // TWO constraints bite here, both found by testing rather than reading docs.
  //
  // 1. `New-ScheduledTaskAction` silently drops -Argument on this machine.
  //    The action registers with an EMPTY Argument, Task Scheduler runs bare
  //    `node.exe`, and the task exits 267009 ("could not start") having written
  //    no log line at all. schtasks.exe round-trips the command correctly.
  //
  // 2. schtasks /TR is capped at 261 characters. This project sits under a long
  //    OneDrive path, so the full node + script + log command is ~380 chars and
  //    is rejected outright. Hence the short wrapper batch file: a 49-character
  //    /TR that expands to the real command at run time.
  //
  // The wrapper also gives us append-only logs, which schtasks cannot do itself.
  const wrapper = path.join(os.homedir(), "AppData", "Roaming", "flasharb-scan.cmd");
  const wrapperBody = [
    "@echo off",
    "REM Flash-arb scanner wrapper. Generated by scripts/schedule-scans.js.",
    "REM Exists because schtasks /TR is capped at 261 characters and this",
    "REM project's OneDrive path alone exceeds that. Safe to delete.",
    `cd /d "${ROOT}"`,
    `"${NODE}" scripts\\scan-flashloan-arb.js --record >> "${logPath}" 2>> "${errPath}"`,
    "",
  ].join("\r\n");
  fs.writeFileSync(wrapper, wrapperBody, "ascii");

  const ps = [
    `$tr = '"${wrapper}"'`,
    `if ($tr.Length -gt 261) { Write-Output 'TR_TOO_LONG'; exit 1 }`,
    `$out = & schtasks.exe /Create /TN "${TASK_NAME}" /TR $tr /SC MINUTE /MO ${MINUTES} /F 2>&1`,
    "$out | Out-Null",
    // Verify by reading the task back. A registration that silently lost its
    // command is a failure that would otherwise surface days later as a
    // mysteriously empty dataset, so check it now.
    `$chk = & schtasks.exe /Query /TN "${TASK_NAME}" /FO LIST /V 2>&1 | Out-String`,
    "if ($chk -match 'flasharb-scan') { Write-Output 'ok' } else { Write-Output 'VERIFY_FAILED'; Write-Output $chk }",
  ].join("; ");

  const out = runScript(ps);
  if (!out.includes("ok")) {
    console.error("Task was created but its command did not survive verification.");
    console.error(out.slice(0, 800));
    console.error("");
    console.error("Unregister it and retry:  node scripts/schedule-scans.js uninstall");
    process.exit(1);
  }


  console.log(`Scheduled task "${TASK_NAME}" installed.`);
  console.log(`  runs every : ${MINUTES} minutes`);
  console.log(`  command    : node scan-flashloan-arb.js --record`);
  console.log(`  working dir: ${ROOT}`);
  console.log(`  logs       : ${logPath}`);
  console.log("");
  console.log("Check it with:  node scripts/schedule-scans.js status");
  console.log("Stop it with:  node scripts/schedule-scans.js uninstall");
}

function status() {
  let found;
  try {
    found = run(
      "Get-ScheduledTask -TaskName " + psQuote(TASK_NAME) +
      " -ErrorAction Stop | Get-ScheduledTaskInfo | ConvertTo-Json",
    );
  } catch (e) {
    console.log(`No scheduled task named "${TASK_NAME}".`);
    console.log("Install one with:  node scripts/schedule-scans.js install");
    return;
  }
  const info = JSON.parse(found);
  // Task Scheduler returns dates in several shapes depending on how the object
  // was serialised: a JSON "/Date(ms)/" wrapper, a plain local-time string, or
  // the 1999 epoch placeholder meaning "never run". Handle all three - the
  // previous version called a perfectly good next-run time "never", which is
  // exactly the kind of false negative that makes a monitor untrustworthy.
  const fmtWhen2 = (v) => {
    if (!v) return "never";
    if (typeof v === "string") {
      const m = v.match(/\/Date\((-?\d+)\)\//);
      if (m) return new Date(Number(m[1])).toLocaleString();
    }
    const ms = Date.parse(v);
    if (Number.isFinite(ms)) {
      const d = new Date(ms);
      // 1999-12-30 is Task Scheduler's "never" sentinel, not a real time.
      if (d.getUTCFullYear() < 2000) return "never";
      return d.toLocaleString();
    }
    return String(v);
  };
  console.log(`task       : ${TASK_NAME}`);
  console.log(`last run   : ${fmtWhen2(info.LastRunTime)}`);
  // 0 = success. 267011 is "task has not yet run", which is expected right
  // after install and is not a failure.
  const lastResult =
    info.LastTaskResult === 0
      ? "success"
      : info.LastTaskResult === 267011
        ? "not run yet"
        : `FAILED (code ${info.LastTaskResult}) - check data/logs/scan-error.log`;
  console.log(`last result: ${lastResult}`);
  console.log(`next run   : ${fmtWhen2(info.NextRunTime)}`);
  console.log(`scans recorded: see data/scan-history.jsonl`);
  try {
    const lines = require("fs")
      .readFileSync(path.join(ROOT, "data", "scan-history.jsonl"), "utf8")
      .split("\n")
      .filter((l) => l.trim()).length;
    console.log(`rows on disk : ${lines}`);
  } catch (e) {
    console.log("rows on disk : 0 (no history file yet)");
  }
}

function uninstall() {
  try {
    run("Unregister-ScheduledTask -TaskName " + psQuote(TASK_NAME) + " -Confirm:$false");
    console.log(`Removed scheduled task "${TASK_NAME}".`);
  } catch (e) {
    console.log(`No scheduled task named "${TASK_NAME}" to remove.`);
  }
}

if (cmd === "install") install();
else if (cmd === "uninstall") uninstall();
else if (cmd === "status") status();
else {
  console.log("Usage: node scripts/schedule-scans.js <install [-Minutes N] | status | uninstall>");
}
